var token = localStorage.getItem("token")
if(!token && typeof(token)!="undefined" && token!=0){
    location.href = "login.html"
}
// 111111111111111111111111111111111111
document.writeln("<div class=\'col-md-3 left_col\'>");
document.writeln("          <div class=\'left_col scroll-view\'>");
document.writeln("            <div class=\'navbar nav_title\' style=\'border: 0;\'>");
document.writeln("              <a href=\'index.html\' class=\'site_title\'><i class=\'fa fa-paw\'></i> <span>Gentelella Alela!</span></a>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'clearfix\'></div>");
document.writeln("");
document.writeln("            <!-- menu profile quick info -->");
document.writeln("            <div class=\'profile clearfix\'>");
document.writeln("              <div class=\'profile_pic\'>");
document.writeln("                <img src=\'images/img.jpg\' alt=\'...\' class=\'img-circle profile_img\'>");
document.writeln("              </div>");
document.writeln("              <div class=\'profile_info\'>");
document.writeln("                <span>Welcome,</span>");
document.writeln("                <h2>John Doe</h2>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("            <!-- /menu profile quick info -->");
document.writeln("");
document.writeln("            <br />");
document.writeln("");
document.writeln("            <!-- sidebar menu -->");
document.writeln("            <div id=\'sidebar-menu\' class=\'main_menu_side hidden-print main_menu\'>");
document.writeln("              <div class=\'menu_section\'>");
document.writeln("                <h3>General</h3>");
document.writeln("                <ul class=\'nav side-menu\'>");
document.writeln("                  <li><a><i class=\'fa fa-home\'></i> 个人中心 <span class=\'fa fa-chevron-down\'></span></a>");
document.writeln("                    <ul class=\'nav child_menu\'>");
document.writeln("                      <li><a href=\'index.html\'>数据概况</a></li>");
document.writeln("                      <li><a href=\'user_info.html\'>我们资料</a></li>");
document.writeln("                      <li><a href=\'index.html\'>我的申请</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a><i class=\'fa fa-home\'></i> 授权管理 <span class=\'fa fa-chevron-down\'></span></a>");
document.writeln("                    <ul class=\'nav child_menu\'>");
document.writeln("                      <li><a href=\'system_user.html\'>授权用户</a></li>");
document.writeln("                      <li><a href=\'system_auth_applications.html\'>授权应用</a></li>");
document.writeln("                      <li><a href=\'index.html\'>申请处理</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a><i class=\'fa fa-edit\'></i> 应用管理 <span class=\'fa fa-chevron-down\'></span></a>");
document.writeln("                    <ul class=\'nav child_menu\'>");
document.writeln("                      <li><a href=\'auth_applications.html\'>我的应用</a></li>");
document.writeln("                      <li><a href=\'index.html\'>申请处理</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a><i class=\'fa fa-desktop\'></i> 用户管理 <span class=\'fa fa-chevron-down\'></span></a>");
document.writeln("                    <ul class=\'nav child_menu\'>");
document.writeln("                      <li><a href=\'auth_users.html\'>我的用户</a></li>");
document.writeln("                      <li><a href=\'index.html\'>申请处理</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("              <div class=\'menu_section\'>");
document.writeln("                <h3>系统管理</h3>");
document.writeln("                <ul class=\'nav side-menu\'>");
document.writeln("                  <li><a><i class=\'fa fa-bug\'></i> 系统设置 <span class=\'fa fa-chevron-down\'></span></a>");
document.writeln("                    <ul class=\'nav child_menu\'>");
document.writeln("                      <li><a href=\'index.html\'>E-commerce</a></li>");
document.writeln("                      <li><a href=\'index.html\'>Projects</a></li>");
document.writeln("                      <li><a href=\'index.html\'>Project Detail</a></li>");
document.writeln("                      <li><a href=\'index.html\'>Contacts</a></li>");
document.writeln("                      <li><a href=\'index.html\'>Profile</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("");
document.writeln("            </div>");
document.writeln("            <!-- /sidebar menu -->");
document.writeln("");
document.writeln("            <!-- /menu footer buttons -->");
document.writeln("            <div class=\'sidebar-footer hidden-small\'>");
document.writeln("              <a data-toggle=\'tooltip\' data-placement=\'top\' title=\'Settings\'>");
document.writeln("                <span class=\'glyphicon glyphicon-cog\' aria-hidden=\'true\'></span>");
document.writeln("              </a>");
document.writeln("              <a data-toggle=\'tooltip\' data-placement=\'top\' title=\'FullScreen\'>");
document.writeln("                <span class=\'glyphicon glyphicon-fullscreen\' aria-hidden=\'true\'></span>");
document.writeln("              </a>");
document.writeln("              <a data-toggle=\'tooltip\' data-placement=\'top\' title=\'Lock\'>");
document.writeln("                <span class=\'glyphicon glyphicon-eye-close\' aria-hidden=\'true\'></span>");
document.writeln("              </a>");
document.writeln("              <a data-toggle=\'tooltip\' data-placement=\'top\' title=\'Logout\' href=\'login.html\'>");
document.writeln("                <span class=\'glyphicon glyphicon-off\' aria-hidden=\'true\'></span>");
document.writeln("              </a>");
document.writeln("            </div>");
document.writeln("            <!-- /menu footer buttons -->");
document.writeln("          </div>");
document.writeln("        </div>");

// 2222222222222222222222222222222222
document.writeln("<!-- top navigation -->");
document.writeln("        <div class=\'top_nav\'>");
document.writeln("          <div class=\'nav_menu\'>");
document.writeln("              <div class=\'nav toggle\'>");
document.writeln("                <a id=\'menu_toggle\'><i class=\'fa fa-bars\'></i></a>");
document.writeln("              </div>");
document.writeln("              <nav class=\'nav navbar-nav\'>");
document.writeln("              <ul class=\' navbar-right\'>");
document.writeln("                <li class=\'nav-item dropdown open\' style=\'padding-left: 15px;\'>");
document.writeln("                  <a href=\'javascript:;\' class=\'user-profile dropdown-toggle\' aria-haspopup=\'true\' id=\'navbarDropdown\' data-toggle=\'dropdown\' aria-expanded=\'false\'>");
document.writeln("                    <img src=\'images/img.jpg\' alt=\'\'>John Doe");
document.writeln("                  </a>");
document.writeln("                  <div class=\'dropdown-menu dropdown-usermenu pull-right\' aria-labelledby=\'navbarDropdown\'>");
document.writeln("                    <a class=\'dropdown-item\'  href=\'javascript:;\'> 我的资料</a>");
document.writeln("                      <a class=\'dropdown-item\'  href=\'javascript:;\'>");
document.writeln("                        <span class=\'badge bg-red pull-right\'>50%</span>");
document.writeln("                        <span>设置</span>");
document.writeln("                      </a>");
document.writeln("                  <a class=\'dropdown-item\'  href=\'javascript:;\'>帮助文档</a>");
document.writeln("                    <a class=\'dropdown-item\'  href=\'login.html\'><i class=\'fa fa-sign-out pull-right\'></i> 退出</a>");
document.writeln("                  </div>");
document.writeln("                </li>");
document.writeln("");
document.writeln("                <li role=\'presentation\' class=\'nav-item dropdown open\'>");
document.writeln("                  <a href=\'javascript:;\' class=\'dropdown-toggle info-number\' id=\'navbarDropdown1\' data-toggle=\'dropdown\' aria-expanded=\'false\'>");
document.writeln("                    <i class=\'fa fa-envelope-o\'></i>");
document.writeln("                    <span class=\'badge bg-green\'>6</span>");
document.writeln("                  </a>");
document.writeln("                  <ul class=\'dropdown-menu list-unstyled msg_list\' role=\'menu\' aria-labelledby=\'navbarDropdown1\'>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'dropdown-item\'>");
document.writeln("                        <span class=\'image\'><img src=\'images/img.jpg\' alt=\'Profile Image\' /></span>");
document.writeln("                        <span>");
document.writeln("                          <span>John Smith</span>");
document.writeln("                          <span class=\'time\'>3 mins ago</span>");
document.writeln("                        </span>");
document.writeln("                        <span class=\'message\'>");
document.writeln("                          Film festivals used to be do-or-die moments for movie makers. They were where...");
document.writeln("                        </span>");
document.writeln("                      </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'dropdown-item\'>");
document.writeln("                        <span class=\'image\'><img src=\'images/img.jpg\' alt=\'Profile Image\' /></span>");
document.writeln("                        <span>");
document.writeln("                          <span>John Smith</span>");
document.writeln("                          <span class=\'time\'>3 mins ago</span>");
document.writeln("                        </span>");
document.writeln("                        <span class=\'message\'>");
document.writeln("                          Film festivals used to be do-or-die moments for movie makers. They were where...");
document.writeln("                        </span>");
document.writeln("                      </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'dropdown-item\'>");
document.writeln("                        <span class=\'image\'><img src=\'images/img.jpg\' alt=\'Profile Image\' /></span>");
document.writeln("                        <span>");
document.writeln("                          <span>John Smith</span>");
document.writeln("                          <span class=\'time\'>3 mins ago</span>");
document.writeln("                        </span>");
document.writeln("                        <span class=\'message\'>");
document.writeln("                          Film festivals used to be do-or-die moments for movie makers. They were where...");
document.writeln("                        </span>");
document.writeln("                      </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'dropdown-item\'>");
document.writeln("                        <span class=\'image\'><img src=\'images/img.jpg\' alt=\'Profile Image\' /></span>");
document.writeln("                        <span>");
document.writeln("                          <span>John Smith</span>");
document.writeln("                          <span class=\'time\'>3 mins ago</span>");
document.writeln("                        </span>");
document.writeln("                        <span class=\'message\'>");
document.writeln("                          Film festivals used to be do-or-die moments for movie makers. They were where...");
document.writeln("                        </span>");
document.writeln("                      </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <div class=\'text-center\'>");
document.writeln("                        <a class=\'dropdown-item\'>");
document.writeln("                          <strong>See All Alerts</strong>");
document.writeln("                          <i class=\'fa fa-angle-right\'></i>");
document.writeln("                        </a>");
document.writeln("                      </div>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </nav>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <!-- /top navigation -->");


